use std::env;
use std::fmt::Write;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let mut generated = String::new();

    generated.push_str("// @generated by crates/nsrl-core/build.rs\n");
    generated.push_str("// Values are q15 approximations of 1 / sqrt(m / 128), m in [128, 255].\n");
    generated.push_str("pub const RSQRT_LUT_8BIT: [i16; 128] = [\n");

    for mantissa in 128_u16..=255 {
        let normalized = f64::from(mantissa) / 128.0;
        let q15 = (32768.0 / normalized.sqrt()).round();
        let q15 = q15.clamp(0.0, f64::from(i16::MAX)) as i16;

        if (mantissa - 128) % 8 == 0 {
            generated.push_str("    ");
        }

        write!(&mut generated, "{q15:5}, ").expect("write to string cannot fail");

        if (mantissa - 127) % 8 == 0 {
            generated.push('\n');
        }
    }

    generated.push_str("];\n");

    generated.push_str("\n// Values are q15 approximations of 2^(-f / 256), f in [0, 255].\n");
    generated.push_str("pub const EXP2_NEG_FRAC_LUT_8BIT: [i16; 256] = [\n");

    for frac in 0_u16..=255 {
        let x = -(f64::from(frac) / 256.0);
        let q15 = (32768.0 * 2.0_f64.powf(x)).round();
        let q15 = q15.clamp(0.0, f64::from(i16::MAX)) as i16;

        if frac % 8 == 0 {
            generated.push_str("    ");
        }

        write!(&mut generated, "{q15:5}, ").expect("write to string cannot fail");

        if (frac + 1) % 8 == 0 {
            generated.push('\n');
        }
    }

    generated.push_str("];\n");

    generated.push_str("\n// Values are q31 approximations of 1 / m, m in [128, 255].\n");
    generated.push_str("pub const RECIP_LUT_8BIT_Q31: [u32; 128] = [\n");

    for mantissa in 128_u32..=255 {
        let q31 = ((1_u64 << 31) + u64::from(mantissa / 2)) / u64::from(mantissa);

        if (mantissa - 128) % 4 == 0 {
            generated.push_str("    ");
        }

        write!(&mut generated, "{q31:10}, ").expect("write to string cannot fail");

        if (mantissa - 127) % 4 == 0 {
            generated.push('\n');
        }
    }

    generated.push_str("];\n");

    fs::write(out_dir.join("rsqrt_lut_8bit.rs"), generated)
        .expect("write generated RSQRT_LUT_8BIT");
}
